server:
  port: 9003

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-MODULE
          uri: lb://USER-MODULE
          predicates:
            - Path=/api/users/**

        - id: COMMUNICATION-MODULE
          uri: lb://COMMUNICATION-MODULE
          predicates:
            - Path=/api/mail/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka