server:
  port: 9002

spring:
  application:
    name: COMMUNICATION-MODULE
  mail:
    host: smtp.gmail.com
    port: 587
    username: jmnaprasad261@gmail.com
    password: kjlw kmvr cczt pevg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true